apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cncf-core
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: nginx-ingress
            chart: ingress-nginx
            repo: https://kubernetes.github.io/ingress-nginx
            namespace: ingress-nginx
            version: 4.11.1
          - name: argo-rollouts
            chart: argo-rollouts
            repo: https://argoproj.github.io/argo-helm
            namespace: argo-rollouts
            version: 2.38.2
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repo}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          releaseName: '{{name}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
