name: PR Validate
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - '.github/workflows/pr-validate.yml'
      - '!**/*.md'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --coverage
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: app/coverage

  docker-build:
    name: Docker build (no push)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build image (no push)
        uses: docker/build-push-action@v6
        with:
          context: app
          push: false
          tags: msd:pr-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
